apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: board-ingress
  namespace: aws-study-board
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/keep-alive-requests: "150"
    nginx.ingress.kubernetes.io/keep-alive: "45"
    nginx.ingress.kubernetes.io/load-balance: "ewma"
spec:
  
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: board-frontend-svc  
            port:
              number: 80               # [핵심] 30300이 아니라 '내부 포트 80'을 적어야 함!
